// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp--0BgNSoJnhV7nIBB9ciHkc249F4YOc',
    appId: '1:228184608661:web:38c88ead8cf9b70263709c',
    messagingSenderId: '228184608661',
    projectId: 'fresherfoods-3b33a',
    authDomain: 'fresherfoods-3b33a.firebaseapp.com',
    storageBucket: 'fresherfoods-3b33a.appspot.com',
    measurementId: 'G-2JL8ED9L9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmyPbeNID45T9MzQnKdTc9447H9zU65Y',
    appId: '1:228184608661:android:6be75d7397f0d72b63709c',
    messagingSenderId: '228184608661',
    projectId: 'fresherfoods-3b33a',
    storageBucket: 'fresherfoods-3b33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoUWOekZ2apGCBskLAQ3Cbau9i0S9JBuM',
    appId: '1:228184608661:ios:aa1a1c4aedcc41e463709c',
    messagingSenderId: '228184608661',
    projectId: 'fresherfoods-3b33a',
    storageBucket: 'fresherfoods-3b33a.appspot.com',
    iosBundleId: 'com.example.fresherfoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoUWOekZ2apGCBskLAQ3Cbau9i0S9JBuM',
    appId: '1:228184608661:ios:bd481f6eb831aac263709c',
    messagingSenderId: '228184608661',
    projectId: 'fresherfoods-3b33a',
    storageBucket: 'fresherfoods-3b33a.appspot.com',
    iosBundleId: 'com.example.fresherfoods.RunnerTests',
  );
}
